#!/usr/bin/env bash

SUDO=$(docker info >/dev/null 2>&1 || echo "sudo -E")

${SUDO} docker run -v "$(pwd)"/docker/tcptracer-ebpf.o:/tcptracer-ebpf.o --entrypoint=/bin/sh \
    weaveworks/scope-backend-build \
    -c 'sha1sum /tcptracer-ebpf.o ; objdump -s --section=build_id /tcptracer-ebpf.o | grep "^ " | xxd -r | tr "\0" "\n" ; echo'
